# config/settings.yaml

# General Application Settings
application:
  name: "AdvancedLanguageModelManager"
  version: "1.0.0"
  environment: "production"  # options: development, testing, production
  debug: false

# Logging Configuration
logging:
  level: "INFO"  # options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/application.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Directory Paths
directories:
  config_dir: "./config"
  logs_dir: "./logs"
  data_dir: "./data"
  models_dir: "./models"

# Security Settings
security:
  encryption:
    algorithm: "AES-256"
    key_length: 32  # in bytes
    iv_length: 16   # in bytes
    key_file: "config/encryption_key.bin"
    iv_file: "config/encryption_iv.bin"

# Database Settings
database:
  vector_database:
    type: "pinecone"
    api_key_encrypted: "config/api_keys_encrypted.enc"  # path to encrypted API keys
    environment: "us-west1-gcp"
    index_name: "language-model-vectors"
  shared_memory:
    type: "redis"
    host: "localhost"
    port: 6379
    db: 0
  time_series:
    type: "influxdb"
    url: "http://localhost:8086"
    token_encrypted: "config/api_keys_encrypted.enc"  # path to encrypted API keys
    org: "my_org"
    bucket: "model_events"

# Service-Specific Settings
services:
  openai:
    api_endpoint: "https://api.openai.com/v1"
    models:
      - "gpt-3.5-turbo"
      - "gpt-4"
      - "text-davinci-003"
  google_palm:
    api_endpoint: "https://generativelanguage.googleapis.com/v1beta2/models"
    models:
      - "models/text-bison-001"
      - "models/text-similarity-bison-001"
      - "models/code-bison-001"
  azure_openai:
    api_endpoint: "https://<your-resource-name>.openai.azure.com"
    api_version: "2023-05-15"
    deployment_name: "text-davinci-003"
    models:
      - "text-davinci-003"
      - "gpt-35-turbo"
  huggingface:
    api_endpoint: "https://api-inference.huggingface.co"
    models:
      - "gpt2"
      - "gpt-j-6B"
      - "EleutherAI/gpt-neo-2.7B"
  anthropic:
    api_endpoint: "https://api.anthropic.com/v1"
    models:
      - "claude-v1"
      - "claude-instant-v1"
  cohere:
    api_endpoint: "https://api.cohere.ai"
    models:
      - "command-xlarge-nightly"
      - "command-medium-nightly"
      - "summarize-xlarge"
